trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo setting up AWS EC2
  displayName: 'Setting up aws ec2'
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceAWS: 'aws-for-terraform'
    backendAWSBucketName: 'terraform-backend-state'
    backendAWSKey: 'kubernetes-dev.tfstate'
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAWS: 'aws-for-terraform'