trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'aws-terraform'
    backendAWSBucketName: 'terraform-backend-state'
    backendAWSKey: 'kubernetes-dev.tfstate'
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'aws-terraform'