trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: aws_key_pair
  displayName: 'Download AWS key pair'
  inputs:
    secureFile: 'administrator.pem'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '**/administrator.pem'
    TargetFolder: '$(HOME)'

- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'aws-terraform'
    backendAWSBucketName: 'terraform-backend-state'
    backendAWSKey: 'kubernetes-dev.tfstate'
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'destroy'
    environmentServiceNameAWS: 'aws-terraform'